

INSERT INTO public.repayment_plans (
    id, name, frequency, periods, base_amount, 
    repayment_per_period, advance_amount, late_fee_per_period, 
    description, created_at, updated_at
) VALUES 
-- Set 1 Records (IDs 1-5)
(1, 'Weekly Micro Plan', 'weekly', 4, 1000.00, 250.00, 0.00, 10.00, 'Short term weekly entry plan', NOW(), NOW()),
(2, 'Standard Monthly 12x', 'monthly', 12, 12000.00, 1000.00, 500.00, 50.00, '12 month standard plan with deposit', NOW(), NOW()),
(3, 'Bi-Weekly Growth', 'bi-weekly', 6, 3000.00, 500.00, 0.00, 25.00, 'Bi-weekly business acceleration scale', NOW(), NOW()),
(4, 'Quarterly Corporate', 'quarterly', 4, 40000.00, 10000.00, 2000.00, 250.00, 'Enterprise tier quarterly payout cycle', NOW(), NOW()),
(5, 'Custom Flexible Tier', 'monthly', 24, 24000.00, 1000.00, 1000.00, 75.00, 'Extended runtime flexible financing option', NOW(), NOW()),

-- Set 2 Records (IDs 6-11)
(6, 'Daily Micro Plan', 'daily', 30, 1500.00, 50.00, 0.00, 5.00, 'Short term daily retail financing tier', NOW(), NOW()),
(7, 'Semi-Monthly Enterprise', 'semi-monthly', 24, 48000.00, 2000.00, 4000.00, 100.00, 'B2B twice-monthly executive repayment program', NOW(), NOW()),
(8, 'Bi-Weekly Pilot', 'bi-weekly', 10, 5000.00, 500.00, 250.00, 30.00, 'Intermediate evaluation structure for standard accounts', NOW(), NOW()),
(9, 'Annual Legacy Payout', 'annually', 1, 10000.00, 10000.00, 1000.00, 500.00, 'Single settlement plan option for long term contracts', NOW(), NOW()),
(10, 'Bi-Monthly Venture', 'bi-monthly', 6, 18000.00, 3000.00, 0.00, 150.00, 'Alternative corporate operational support cycle', NOW(), NOW()),
(11, 'Custom Seasonal Plan', 'monthly', 3, 9000.00, 3000.00, 500.00, 40.00, 'Short interval holiday cycle support financing', NOW(), NOW());



INSERT INTO public.customer_types (status_name, description) 
VALUES 
('Retail', 'Standard individual retail consumer account'),
('Wholesale', 'Business-to-business bulk purchase tier'),
('Premium', 'High-volume user with dedicated support'),
('VIP', 'Invite-only early access account category'),
('Enterprise', 'Corporate clients with custom contract agreements');



















INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));
INSERT INTO public.customer_types (id, status_name, description, created_at, updated_at, sequence_id) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(status_name), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL') || ', ' || COALESCE(quote_literal(sequence_id), 'NULL'));

INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
INSERT INTO public.repayment_plans (id, name, frequency, periods, base_amount, repayment_per_period, advance_amount, late_fee_per_period, description, created_at, updated_at) VALUES (COALESCE(quote_literal(id), 'NULL') || ', ' || COALESCE(quote_literal(name), 'NULL') || ', ' || COALESCE(quote_literal(frequency), 'NULL') || ', ' || COALESCE(quote_literal(periods), 'NULL') || ', ' || COALESCE(quote_literal(base_amount), 'NULL') || ', ' || COALESCE(quote_literal(repayment_per_period), 'NULL') || ', ' || COALESCE(quote_literal(advance_amount), 'NULL') || ', ' || COALESCE(quote_literal(late_fee_per_period), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(created_at), 'NULL') || ', ' || COALESCE(quote_literal(updated_at), 'NULL'));
